export default {
    pericias: [
        {
            nome: "Acrobacia",
            carga: true,
            treinada: false,
        },
        {
            nome: "Adestramento",
            carga: false,
            treinada: true,
        },
        {
            nome: "Artes",
            carga: false,
            treinada: true,
        },
        {
            nome: "Atletismo",
            carga: false,
            treinada: false,
        },
        {
            nome: "Atualidades",
            carga: false,
            treinada: false,
        },
        {
            nome: "Ciências",
            carga: false,
            treinada: true,
        },
        {
            nome: "Crime",
            carga: true,
            treinada: true,
        },
        {
            nome: "Diplomacia",
            carga: false,
            treinada: false,
        },
        {
            nome: "Enganação",
            carga: false,
            treinada: false,
        },
        {
            nome: "Fortitude",
            carga: false,
            treinada: false,
        },
        {
            nome: "Furtividade",
            carga: true,
            treinada: false,
        },
        {
            nome: "Iniciativa",
            carga: false,
            treinada: false,
        },
        {
            nome: "Intimidação",
            carga: false,
            treinada: false,
        },
        {
            nome: "Intuição",
            carga: false,
            treinada: false,
        },
        {
            nome: "Investigação",
            carga: false,
            treinada: false,
        },
        {
            nome: "Luta",
            carga: false,
            treinada: false,
        },
        {
            nome: "Medicina",
            carga: false,
            treinada: false,
        },
        {
            nome: "Ocultismo",
            carga: false,
            treinada: true,
        },
        {
            nome: "Percepção",
            carga: false,
            treinada: false,
        },
        {
            nome: "Pilotagem",
            carga: false,
            treinada: true,
        },
        {
            nome: "Pontaria",
            carga: false,
            treinada: false,
        },
        {
            nome: "Profissão",
            carga: false,
            treinada: true,
        },
        {
            nome: "Reflexos",
            carga: false,
            treinada: false,
        },
        {
            nome: "Religião",
            carga: false,
            treinada: true,
        },
        {
            nome: "Sobrevivência",
            carga: false,
            treinada: false,
        },
        {
            nome: "Tática",
            carga: false,
            treinada: true,
        },
        {
            nome: "Tecnologia",
            carga: false,
            treinada: true,
        },
        {
            nome: "Vontade",
            carga: false,
            treinada: false,
        },
    ],
    origens: [
        "Acadêmico",
        "Agente de Saúde",
        "Amnésico",
        "Artista",
        "Atleta",
        "Chef",
        "Criminoso",
        "Cultista Arrependido",
        "Desgarrado",
        "Engenheiro",
        "Executivo",
        "Investigador",
        "Lutador",
        "Magnata",
        "Militar",
        "Operário",
        "Policial",
        "Religioso",
        "Servidor Público",
        "Teórico da Conspiração",
        "T.I.",
        "Trabalhador Rural",
        "Trambiqueiro",
        "Universitário",
        "Vítima",
    ],
    trilhas: {
        combatente: [
            "Aniquilador",
            "Comandante de Campo",
            "Guerreiro",
            "Operações Especiais",
            "Tropa de Choque",
        ],
        especialista: [
            "Atirador de Elite",
            "Infiltrador",
            "Médico de Campo",
            "Negociador",
            "Técnico",
        ],
        ocultista: [
            "Conduíte",
            "Flagelador",
            "Graduado",
            "Intuitivo",
            "Lâmina Paranormal",
        ],
    },
    proficiências: [
        "Armas Simples",
        "Armas Táticas",
        "Armas Pesadas",
        "Proteções Leves",
        "Proteções Pesadas",
    ],
};
